---
- name: Installa PHP-FPM e le estensioni
  ansible.builtin.apt:
    name: "{{ php_extensions }}"
    state: present

- name: Installa redis-php se Redis abilitato
  ansible.builtin.apt:
    name: "php{{ php_version }}-redis"
    state: present
  when: enable_redis | bool

- name: Configura i limiti PHP (php.ini FPM)
  ansible.builtin.template:
    src: 99-wordpress.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/conf.d/99-wordpress.ini"
    mode: "0644"
  notify: Restart php-fpm

- name: Configura il pool FPM
  ansible.builtin.template:
    src: pool.conf.j2
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ php_fpm_pool }}.conf"
    mode: "0644"
  notify: Restart php-fpm

- name: Abilita e avvia PHP-FPM
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    enabled: true
    state: started
